stateDiagram-v2
    [*] --> Create_Decision
    Create_Decision --> Assigned
    Create_Decision --> Pending_Assignment
    New --> Assigned
    New --> Pending_Assignment
    Pending_Assignment --> Assigned
    Assigned --> In_Review
    Assigned --> Rejected
    In_Review --> Need_More_Information
    Need_More_Information --> In_Review
    In_Review --> In_Progress
    In_Review --> Rejected
    In_Progress --> Resolved
    Resolved --> Retest_Required
    Resolved --> Closed
    Retest_Required --> Closed
    Retest_Required --> Reopened
    Resolved --> Reopened
    Closed --> Reopened
    Reopened --> Assigned
    Rejected --> Assigned
    Rejected --> Pending_Assignment
    Closed --> [*]
