"""Generate SAP490 functional specification and updated bug-fix workbooks."""

from __future__ import annotations

from copy import copy
from datetime import date
from pathlib import Path
import shutil

from openpyxl import load_workbook
from openpyxl.cell.cell import MergedCell
from openpyxl.styles import Alignment


ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_DIR = ROOT / "docs" / "sap490" / "templates" / "Deliverable_template"
OUTPUT_DIR = ROOT / "docs" / "sap490" / "generated"
DOCUMENT_DATE = date(2026, 6, 16)
FUNCTIONAL_VERSION = "0.1"
BUGFIX_VERSION = "0.2"


LABELS = {
    "en": {
        "functional_title": "Functional Specification",
        "module": "Module",
        "module_name": "Module Name",
        "function_id": "Function ID",
        "function_name": "Function Name",
        "created_date": "Created Date",
        "updated_date": "Last Update Date",
        "approver": "Approver",
        "reviewer": "Reviewer",
        "creator": "Creator",
        "history_description": "Initial SAP490 functional specification for IDTS Fiori Bug Management MVP.",
        "function_overview": [
            "This function allows internal Testers to create, classify, assign, and review bug reports through the SAP Fiori Elements Bug Management app.",
            "The current MVP focuses on List Report, Object Page, full-page Create Bug flow, value helps, assignment visibility, lifecycle actions, comments/history visibility, and notification records.",
            "The implementation remains metadata-driven through CAP CDS annotations and OData V4. Custom SAPUI5 is deferred unless annotations are insufficient.",
        ],
        "process_flow": [
            "1. Tester opens the Bug Management List Report and selects Create Bug.",
            "2. Fiori opens the draft Object Page in create mode.",
            "3. Tester enters General Information: title, description, priority, severity, and environment.",
            "4. Tester selects Classification and Assignment: SAP module if relevant, application component, defect category, and optional assignee.",
            "5. Assignee value help shows business columns and filters candidates by the selected component/category where available.",
            "6. Tester enters Reproduction and Test Context: steps, actual result, expected result, and optional test references.",
            "7. System validates mandatory fields, derives component category, overwrites system-managed fields, creates history, and starts in Assigned or Pending Assignment.",
            "8. Developer/PM later use the Object Page actions for review, request information, reject, resolve, retest, close, or reopen.",
        ],
        "screen_layout_note": "Target C-prime Object Page layout: General Information first, Classification and Assignment second, Reproduction and Test Context third. Active-only tables are hidden during creation.",
        "screen_items": [
            ("Title", "title", "Section 1 - General Information", "Mandatory text entered by Tester"),
            ("Description", "description", "Section 1 - General Information", "Mandatory multiline text"),
            ("Priority", "priority_code", "Section 1 - General Information", "Mandatory value help"),
            ("Severity", "severity_code", "Section 1 - General Information", "Mandatory value help"),
            ("Environment", "environment_code", "Section 1 - General Information", "Optional value help"),
            ("SAP Module", "sapModule_ID", "Section 2 - Classification and Assignment", "Optional value help context and assignment filter"),
            ("Application Component", "applicationComponent_ID", "Section 2 - Classification and Assignment", "Mandatory value help"),
            ("Defect Category", "defectCategory_ID", "Section 2 - Classification and Assignment", "Mandatory value help"),
            ("Assignee", "assignee_ID", "Section 2 - Classification and Assignment", "Optional value help; blank means Pending Assignment"),
            ("Steps to Reproduce", "stepsToReproduce", "Section 3 - Reproduction and Test Context", "Mandatory multiline text"),
            ("Actual Result", "actualResult", "Section 3 - Reproduction and Test Context", "Mandatory multiline text"),
            ("Expected Result", "expectedResult", "Section 3 - Reproduction and Test Context", "Mandatory multiline text"),
            ("Test Case Reference", "testCaseRef", "Section 3 - Reproduction and Test Context", "Optional reference"),
            ("Test Run Reference", "testRunRef", "Section 3 - Reproduction and Test Context", "Optional reference"),
            ("Bug Number", "bugNumber", "Header/System", "Generated by backend, read-only"),
            ("Status", "status_code", "Header/System", "Generated/controlled by backend lifecycle, read-only at create"),
            ("Reporter", "reporter_ID", "Header/System", "Derived from logged-in user or local fallback, read-only"),
            ("Next Processor", "nextProcessorUser_ID / nextProcessorRole_code", "Active-only follow-up", "System-maintained after creation, read-only"),
        ],
        "messages": [
            ("IDTS-FE-001", "English", "Please fill in all mandatory bug report fields before saving.", "On save/activate draft"),
            ("IDTS-FE-002", "English", "No suitable developer was selected. The bug will remain Pending Assignment.", "On create without assignee"),
            ("IDTS-FE-003", "English", "The selected assignee is not responsible for the chosen component/category.", "On assignment validation"),
            ("IDTS-FE-004", "English", "A reason is required for this lifecycle transition.", "On request information, reject, resolve, or reopen when required"),
        ],
        "processing": [
            "System hides system-managed and active-only collaboration sections while creating a new draft. Comments, history, notifications, planning, rejected follow-up, status, reporter, next processor, created date, and updated date are not editable during creation. Evidence files may be selected during create and are uploaded after the bug is saved.",
            "Assignee uses a dedicated AssignableDevelopers value help projection with developer name, email, availability, application component, defect category, SAP module scope, and responsibility level.",
            "After assignee selection, side effects refresh assigneeDisplayName so the UI displays the developer name instead of the raw UUID.",
            "On create, CAP handlers overwrite bugNumber, status_code, and reporter_ID. Client-provided values for system-managed fields are not trusted.",
            "If assignee is selected, the bug proceeds to Assigned. If assignee is blank, the bug proceeds to Pending Assignment and nextProcessor points to the appropriate follow-up queue.",
        ],
        "bug_headers": ["No", "Bug", "Details", "Expected result", "Fix"],
        "bugs": [
            (
                "IDTS-5 - SC-01a direct CAP CREATE verification failed",
                "Merged QA harness dispatched CREATE without an INSERT query, then exposed a missing explicit UUID.",
                "A valid bug request is created successfully and the complete backend suite passes.",
                "Added INSERT query and explicit UUIDs; rerun result: 21/21 PASS.",
            ),
            (
                "WP4 - Assignee value help showed technical columns and labels",
                "Assignee picker displayed developerProfile_ID and responsibilityLevel_code; common value helps also used generic headers such as code and name.",
                "Assignee and common value helps show business-readable labels and columns.",
                "Added AssignableDevelopers projection, value-list annotations, and property-level labels.",
            ),
            (
                "WP4 - Selected Assignee displayed raw UUID",
                "After selecting a developer, the Assignee field showed the DeveloperProfile UUID instead of the user display name.",
                "Assignee field displays the selected developer display name, for example DatDT.",
                "Added assigneeDisplayName projection/enrichment for active and draft reads plus side-effect refresh.",
            ),
            (
                "WP4 - Create layout was not aligned with Tester mental flow",
                "Assignment-first layout surfaced technical assignment controls before the user had described the bug.",
                "Create/Object Page follows General Information, Classification and Assignment, then Reproduction and Test Context.",
                "Recorded C-prime as the target layout for the next WP4 UI refinement baseline.",
            ),
        ],
    },
    "vi": {
        "functional_title": "Đặc tả chức năng",
        "module": "Mô-đun",
        "module_name": "Tên mô-đun",
        "function_id": "Mã chức năng",
        "function_name": "Tên chức năng",
        "created_date": "Ngày tạo",
        "updated_date": "Ngày cập nhật",
        "approver": "Người phê duyệt",
        "reviewer": "Người rà soát",
        "creator": "Người tạo",
        "history_description": "Khởi tạo đặc tả chức năng SAP490 cho MVP Fiori Bug Management của IDTS.",
        "function_overview": [
            "Chức năng này cho phép Tester nội bộ tạo, phân loại, gán người xử lý và theo dõi bug report thông qua ứng dụng SAP Fiori Elements Bug Management.",
            "MVP hiện tập trung vào List Report, Object Page, luồng Create Bug dạng full-page, value help, assignment visibility, lifecycle actions, comments/history visibility và notification records.",
            "Triển khai vẫn ưu tiên metadata-driven thông qua CAP CDS annotations và OData V4. Custom SAPUI5 chỉ dùng sau này nếu annotation không đủ.",
        ],
        "process_flow": [
            "1. Tester mở Bug Management List Report và chọn Create Bug.",
            "2. Fiori mở draft Object Page ở chế độ tạo mới.",
            "3. Tester nhập General Information: title, description, priority, severity và environment.",
            "4. Tester chọn Classification and Assignment: SAP module nếu liên quan, application component, defect category và assignee nếu có.",
            "5. Value help Assignee hiển thị cột nghiệp vụ và lọc candidate theo component/category đã chọn khi có thể.",
            "6. Tester nhập Reproduction and Test Context: steps, actual result, expected result và test reference tùy chọn.",
            "7. Hệ thống validate mandatory fields, derive component category, ghi đè system-managed fields, tạo history và bắt đầu ở Assigned hoặc Pending Assignment.",
            "8. Developer/PM dùng Object Page actions sau đó để review, request information, reject, resolve, retest, close hoặc reopen.",
        ],
        "screen_layout_note": "Target layout Object Page C-prime: General Information trước, Classification and Assignment thứ hai, Reproduction and Test Context thứ ba. Các bảng active-only được ẩn khi tạo mới.",
        "screen_items": [
            ("Title", "title", "Section 1 - General Information", "Tester nhập bắt buộc"),
            ("Description", "description", "Section 1 - General Information", "Multiline text bắt buộc"),
            ("Priority", "priority_code", "Section 1 - General Information", "Value help bắt buộc"),
            ("Severity", "severity_code", "Section 1 - General Information", "Value help bắt buộc"),
            ("Environment", "environment_code", "Section 1 - General Information", "Value help tùy chọn"),
            ("SAP Module", "sapModule_ID", "Section 2 - Classification and Assignment", "Ngữ cảnh value help tùy chọn và filter assignment"),
            ("Application Component", "applicationComponent_ID", "Section 2 - Classification and Assignment", "Value help bắt buộc"),
            ("Defect Category", "defectCategory_ID", "Section 2 - Classification and Assignment", "Value help bắt buộc"),
            ("Assignee", "assignee_ID", "Section 2 - Classification and Assignment", "Value help tùy chọn; để trống nghĩa là Pending Assignment"),
            ("Steps to Reproduce", "stepsToReproduce", "Section 3 - Reproduction and Test Context", "Multiline text bắt buộc"),
            ("Actual Result", "actualResult", "Section 3 - Reproduction and Test Context", "Multiline text bắt buộc"),
            ("Expected Result", "expectedResult", "Section 3 - Reproduction and Test Context", "Multiline text bắt buộc"),
            ("Test Case Reference", "testCaseRef", "Section 3 - Reproduction and Test Context", "Reference tùy chọn"),
            ("Test Run Reference", "testRunRef", "Section 3 - Reproduction and Test Context", "Reference tùy chọn"),
            ("Bug Number", "bugNumber", "Header/System", "Backend sinh tự động, read-only"),
            ("Status", "status_code", "Header/System", "Backend/lifecycle quản lý, read-only khi tạo"),
            ("Reporter", "reporter_ID", "Header/System", "Lấy từ user đăng nhập hoặc fallback local, read-only"),
            ("Next Processor", "nextProcessorUser_ID / nextProcessorRole_code", "Active-only follow-up", "Hệ thống tự duy trì sau khi tạo, read-only"),
        ],
        "messages": [
            ("IDTS-FE-001", "Vietnamese", "Vui lòng nhập đầy đủ các trường bắt buộc trước khi lưu bug report.", "Khi save/activate draft"),
            ("IDTS-FE-002", "Vietnamese", "Chưa chọn developer phù hợp. Bug sẽ ở trạng thái Pending Assignment.", "Khi tạo bug không có assignee"),
            ("IDTS-FE-003", "Vietnamese", "Developer được chọn không phụ trách component/category này.", "Khi validate assignment"),
            ("IDTS-FE-004", "Vietnamese", "Transition này bắt buộc phải có lý do hoặc ghi chú.", "Khi request information, reject, resolve hoặc reopen nếu bắt buộc"),
        ],
        "processing": [
            "Hệ thống ẩn các section collaboration system-managed và active-only khi tạo draft mới. Comments, history, notifications, planning, rejected follow-up, status, reporter, next processor, created date và updated date không được edit khi tạo mới. Evidence files có thể được chọn trong lúc create và được upload sau khi bug được lưu.",
            "Assignee dùng projection value help riêng AssignableDevelopers với developer name, email, availability, application component, defect category, SAP module scope và responsibility level.",
            "Sau khi chọn assignee, side effect refresh assigneeDisplayName để UI hiển thị tên developer thay vì UUID.",
            "Khi tạo bug, CAP handler ghi đè bugNumber, status_code và reporter_ID. Client không được tự quyết định các trường system-managed.",
            "Nếu chọn assignee, bug chuyển sang Assigned. Nếu để trống assignee, bug chuyển sang Pending Assignment và nextProcessor trỏ tới queue follow-up phù hợp.",
        ],
        "bug_headers": ["STT", "Lỗi", "Chi tiết", "Kết quả mong đợi", "Cách sửa"],
        "bugs": [
            (
                "IDTS-5 - SC-01a lỗi verify CAP CREATE trực tiếp",
                "QA harness sau khi merge gọi CREATE thiếu INSERT query, sau đó phát hiện thiếu UUID tường minh.",
                "Request tạo bug hợp lệ thành công và toàn bộ backend suite pass.",
                "Đã thêm INSERT query và UUID tường minh; kết quả chạy lại: 21/21 PASS.",
            ),
            (
                "WP4 - Value help Assignee hiển thị cột và label kỹ thuật",
                "Popup chọn Assignee hiển thị developerProfile_ID và responsibilityLevel_code; các value help phổ biến cũng dùng header chung như code và name.",
                "Assignee và các value help phổ biến hiển thị label/cột dễ hiểu theo nghiệp vụ.",
                "Đã thêm projection AssignableDevelopers, annotation value list và property-level label.",
            ),
            (
                "WP4 - Assignee đã chọn hiển thị UUID",
                "Sau khi chọn developer, field Assignee hiển thị UUID của DeveloperProfile thay vì display name.",
                "Field Assignee hiển thị tên developer được chọn, ví dụ DatDT.",
                "Đã thêm projection/enrichment assigneeDisplayName cho active và draft reads, kèm side-effect refresh.",
            ),
            (
                "WP4 - Layout Create chưa khớp mental flow của Tester",
                "Layout Assignment-first đưa các control kỹ thuật lên trước khi user mô tả bug.",
                "Create/Object Page đi theo General Information, Classification and Assignment, rồi Reproduction and Test Context.",
                "Ghi nhận C-prime là target layout cho baseline UI refinement tiếp theo của WP4.",
            ),
        ],
    },
}


def copy_template(template_name: str, output_name: str) -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output = OUTPUT_DIR / output_name
    shutil.copy2(TEMPLATE_DIR / template_name, output)
    return output


def write(ws, cell: str, value, *, wrap: bool = False):
    target = ws[cell]
    if isinstance(target, MergedCell):
        for merged_range in ws.merged_cells.ranges:
            if target.coordinate in merged_range:
                target = ws.cell(merged_range.min_row, merged_range.min_col)
                break
    target.value = value
    if isinstance(value, date):
        target.number_format = "yyyy-mm-dd"
    if wrap:
        old = copy(target.alignment)
        target.alignment = Alignment(
            horizontal=old.horizontal,
            vertical=old.vertical or "top",
            text_rotation=old.text_rotation,
            wrap_text=True,
            shrink_to_fit=old.shrink_to_fit,
            indent=old.indent,
        )


def copy_row_style(ws, source_row: int, target_row: int, max_column: int):
    ws.row_dimensions[target_row].height = ws.row_dimensions[source_row].height
    for column in range(1, max_column + 1):
        source = ws.cell(source_row, column)
        target = ws.cell(target_row, column)
        if source.has_style:
            target._style = copy(source._style)
        target.number_format = source.number_format
        target.alignment = copy(source.alignment)
        target.protection = copy(source.protection)


def fill_cover(wb, labels: dict, version: str):
    ws = wb["Cover"]
    write(ws, "B8", labels["functional_title"].upper())
    write(ws, "I11", labels["module"])
    write(ws, "N11", "IDTS")
    write(ws, "U11", labels["module_name"])
    write(ws, "Z11", "Issue and Defect Tracking System in SAP")
    write(ws, "I12", labels["created_date"])
    write(ws, "N12", DOCUMENT_DATE)
    write(ws, "U12", labels["updated_date"])
    write(ws, "Z12", DOCUMENT_DATE)
    write(ws, "U16", labels["approver"])
    write(ws, "Z16", labels["reviewer"])
    write(ws, "AE16", labels["creator"])
    write(ws, "AE17", "DonHV")
    wb.properties.title = f"IDTS SAP490 Functional Specification v{version}"
    wb.properties.subject = "Fiori Bug Management functional specification"
    wb.properties.creator = "IDTS SAP01 Team"


def fill_histories(wb, labels: dict, version: str):
    ws = wb["Histories"]
    write(ws, "B3", 1)
    write(ws, "C3", version)
    write(ws, "D3", labels["history_description"], wrap=True)
    write(ws, "E3", "All functional sheets")
    write(ws, "F3", DOCUMENT_DATE)
    write(ws, "G3", "DonHV")
    for row in range(4, 20):
        for col in range(2, 8):
            ws.cell(row, col).value = None


def fill_function_overview(wb, labels: dict):
    ws = wb["Function Overview"]
    write(ws, "I3", "IDTS-FE-BUG-MGMT")
    write(ws, "B14", "Function Overview")
    for offset, text in enumerate(labels["function_overview"], start=15):
        write(ws, f"B{offset}", text, wrap=True)
        ws.row_dimensions[offset].height = 42
    write(ws, "B20", "Supplement")
    write(ws, "B21", "The UI is implemented with SAP Fiori Elements List Report/Object Page and CAP OData V4 service metadata.", wrap=True)


def fill_process_flow(wb, labels: dict):
    ws = wb["Process Flow"]
    write(ws, "B3", "IDTS-FE-BUG-MGMT")
    write(ws, "P3", "Bug Management Create and Review Flow")
    write(ws, "B5", "Screen Flow")
    for row, step in enumerate(labels["process_flow"], start=6):
        write(ws, f"B{row}", step, wrap=True)
        ws.row_dimensions[row].height = 36
    write(ws, "B44", "Supplement")
    write(ws, "B45", "The Create Bug flow uses a draft Object Page, not a modal dialog, because the report contains more than eight meaningful fields.", wrap=True)


def fill_screen_layout(wb, labels: dict):
    ws = wb["Screen Layout"]
    write(ws, "B2", "Screen Layout")
    write(ws, "B4", labels["screen_layout_note"], wrap=True)
    headers = [("C27", "No."), ("F27", "Field name"), ("N27", "Technical name"), ("S27", "Place"), ("AA27", "Logic")]
    for cell, value in headers:
        write(ws, cell, value)
    write(ws, "C28", 1)
    write(ws, "F28", "Main Create/Edit Fields", wrap=True)
    write(ws, "S28", "Object Page content", wrap=True)
    write(ws, "AA28", labels["screen_layout_note"], wrap=True)
    target_rows = [29, 30, 31, 33, 35, 37, 38, 39, 41, 43, 45, 47, 49, 50]
    for number, ((name, technical, place, logic), target_row) in enumerate(
        zip(labels["screen_items"][:14], target_rows), start=2
    ):
        if target_row > 45:
            copy_row_style(ws, 45, target_row, 35)
        write(ws, f"C{target_row}", number)
        write(ws, f"F{target_row}", name, wrap=True)
        write(ws, f"N{target_row}", technical, wrap=True)
        write(ws, f"S{target_row}", place, wrap=True)
        write(ws, f"AA{target_row}", logic, wrap=True)
        ws.row_dimensions[target_row].height = 34
    for row in [51, 52, 54]:
        for column in [3, 6, 14, 19, 27]:
            cell = ws.cell(row, column)
            if not isinstance(cell, MergedCell):
                cell.value = None


def fill_screen_definition(wb, labels: dict):
    ws = wb["Screen Definition"]
    write(ws, "B3", "IDTS-FE-BUG-MGMT")
    write(ws, "P3", "Bug Management Create and Review Flow")
    write(ws, "B5", "New Bug / Bug Detail")
    write(ws, "B9", "1. Bug Object Page")
    write(ws, "B12", "1.1 Main Create/Edit Fields")
    for row in range(13, 80):
        for col in range(2, 60):
            cell = ws.cell(row, col)
            if not isinstance(cell, MergedCell):
                cell.value = None
    target_rows = [13, 14, 15, 17, 20, 22, 25, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 50]
    for number, ((name, technical, _place, logic), target_row) in enumerate(
        zip(labels["screen_items"], target_rows), start=1
    ):
        if target_row > 44:
            copy_row_style(ws, 44, target_row, 59)
        write(ws, f"B{target_row}", number)
        write(ws, f"C{target_row}", name, wrap=True)
        write(ws, f"I{target_row}", "Input" if "System" not in logic and "read-only" not in logic else "Display")
        write(ws, f"M{target_row}", "I/O" if "read-only" not in logic and "System" not in logic and "Hệ thống" not in logic else "O")
        write(ws, f"O{target_row}", "Single")
        write(ws, f"R{target_row}", technical, wrap=True)
        write(ws, f"U{target_row}", "-")
        write(ws, f"X{target_row}", "-")
        write(ws, f"AA{target_row}", "Yes" if "Mandatory" in logic or "bắt buộc" in logic else "No")
        write(ws, f"AE{target_row}", "Backend default" if "Generated" in logic or "Backend" in logic else "")
        write(ws, f"AI{target_row}", "Text / Value Help")
        write(ws, f"AM{target_row}", "Left")
        write(ws, f"AQ{target_row}", "Yes" if "value help" in logic.lower() else "No")
        write(ws, f"AW{target_row}", logic, wrap=True)
        ws.row_dimensions[target_row].height = 34


def fill_message_definition(wb, labels: dict):
    ws = wb["Message Definition"]
    write(ws, "B3", "IDTS-FE-BUG-MGMT")
    write(ws, "P3", "Bug Management Create and Review Flow")
    for row in range(6, 30):
        for col in range(2, 40):
            cell = ws.cell(row, col)
            if not isinstance(cell, MergedCell):
                cell.value = None
    for row, (message_id, lang, message, timing) in enumerate(labels["messages"], start=6):
        if row > 6:
            copy_row_style(ws, 6, row, 40)
        write(ws, f"B{row}", message_id)
        write(ws, f"F{row}", lang)
        write(ws, f"J{row}", message, wrap=True)
        write(ws, f"AG{row}", timing, wrap=True)
        ws.row_dimensions[row].height = 36


def fill_processing_description(wb, labels: dict):
    ws = wb["Processing Description"]
    write(ws, "B3", "IDTS-FE-BUG-MGMT")
    write(ws, "P3", "Bug Management Create and Review Flow")
    write(ws, "AQ2", "Created by:")
    write(ws, "AY2", "DonHV")
    write(ws, "AQ3", "Modified by:")
    write(ws, "AY3", "DonHV")
    write(ws, "B4", "Processing Description")
    for row, text in enumerate(labels["processing"], start=6):
        write(ws, f"B{row}", text, wrap=True)
        ws.row_dimensions[row].height = 42


def generate_functional_spec(language: str) -> Path:
    labels = LABELS[language]
    output = copy_template(
        "Functional_Specification.xlsx",
        f"Functional_Specification_IDTS_SAP01_{language}_v{FUNCTIONAL_VERSION}.xlsx",
    )
    wb = load_workbook(output)
    fill_cover(wb, labels, FUNCTIONAL_VERSION)
    fill_histories(wb, labels, FUNCTIONAL_VERSION)
    fill_function_overview(wb, labels)
    fill_process_flow(wb, labels)
    fill_screen_layout(wb, labels)
    fill_screen_definition(wb, labels)
    fill_message_definition(wb, labels)
    fill_processing_description(wb, labels)
    wb.save(output)
    return output


def generate_bugfix(language: str) -> Path:
    labels = LABELS[language]
    output = copy_template(
        "Test_And_Fix_Bug.xlsx",
        f"Test_And_Fix_Bug_IDTS_SAP01_{language}_v{BUGFIX_VERSION}.xlsx",
    )
    wb = load_workbook(output)
    wb.properties.title = f"IDTS SAP490 Test and Fix Bug {language.upper()} v{BUGFIX_VERSION}"
    wb.properties.subject = "Sprint 02 backend and Fiori UI defects and fixes"
    wb.properties.creator = "IDTS SAP01 Team"
    ws = wb["Fix and bugs"]
    for cell, value in zip(("A1", "B1", "C1", "D1", "E1"), labels["bug_headers"]):
        write(ws, cell, value)
    target_rows = [2, 3, 5, 6]
    for number, (bug, target_row) in enumerate(zip(labels["bugs"], target_rows), start=1):
        write(ws, f"A{target_row}", number)
        write(ws, f"B{target_row}", bug[0], wrap=True)
        write(ws, f"C{target_row}", bug[1], wrap=True)
        write(ws, f"D{target_row}", bug[2], wrap=True)
        write(ws, f"E{target_row}", bug[3], wrap=True)
        write(ws, f"F{target_row}", "WP4 / Sprint 02 evidence")
        ws.row_dimensions[target_row].height = 78
    for row in [7]:
        for column in range(1, 7):
            cell = ws.cell(row, column)
            if not isinstance(cell, MergedCell):
                cell.value = None
                cell.hyperlink = None
    wb.save(output)
    return output


def main():
    outputs = []
    for language in ("en",):
        outputs.append(generate_functional_spec(language))
        outputs.append(generate_bugfix(language))
    for output in outputs:
        print(output.relative_to(ROOT))


if __name__ == "__main__":
    main()
