"""Validate canonical SAP490 test data and official-template-filled workbooks."""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import unquote

from openpyxl import load_workbook
from openpyxl.cell.cell import MergedCell
from openpyxl.utils import get_column_letter


ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = ROOT / "docs" / "qa" / "test-catalog.json"
OUTPUT_DIR = ROOT / "docs" / "sap490" / "generated"
VALID_STATUSES = {
    "PASSED",
    "FAILED",
    "BLOCKED",
    "NOT_RUN",
    "PENDING",
    "PREPARED",
    "N/A",
}
REQUIRED_CASE_FIELDS = {
    "caseId",
    "testType",
    "requirementIds",
    "title",
    "objective",
    "role",
    "preconditions",
    "testData",
    "steps",
    "expectedResult",
    "actualResult",
    "status",
    "environment",
    "executor",
    "executionDate",
    "automationCommand",
    "evidenceLinks",
    "defectIds",
    "limitations",
    "postcondition",
}
FORBIDDEN = (
    re.compile(r"#REF!", re.I),
    re.compile(r"\bTODO\b", re.I),
    re.compile(r"\bTBD\b", re.I),
    re.compile(r"\bvx\.x\b", re.I),
    re.compile(r"Run the exact npm command in Note", re.I),
    re.compile(r"\bCodex\b", re.I),
    re.compile(r"\bChatGPT\b", re.I),
    re.compile(r"generated by (?:an? )?AI", re.I),
    re.compile(
        r"<(?:Project|Date|List|Feature|Brief|ID\d?|Test case|Describe)[^>]*>",
        re.I,
    ),
)
VI_UNTRANSLATED_EXACT = {
    "Module",
    "Module Name",
    "Function ID",
    "Function Name",
    "Created Date",
    "Last Update Date",
    "Approver",
    "Reviewer",
    "Creator",
    "Description",
    "Modified date",
    "Modified by",
    "Business Flow",
    "Test Contents",
    "Test Cases",
    "Test Data",
    "Predicted Test Results",
    "Test Results",
    "Test Date",
    "Result",
    "Evidence",
    "Remarks",
    "Project Name",
    "Project Code",
    "Issue Date",
    "Document Code",
    "Record of change",
    "Effective Date",
    "Change description",
    "Reference",
    "Test Environment Setup Description",
    "Sheet Name",
    "Pre-Condition",
    "Reviewer/Approver",
    "Notes",
    "Module code",
    "Number of  test cases",
    "Sub total",
    "Test requirement",
    "Number of TCs",
    "Testing Round",
    "Test Case Description",
    "Test Case Procedure",
    "Expected Results",
    "Pre-conditions",
}

FILE_PATTERNS = {
    "scenario": "Test_Scenario_IDTS_SAP01_{lang}_v0.3.xlsx",
    "unit": "Unit_Test_IDTS_SAP01_{lang}_v0.4.xlsx",
    "functional": "Functional_Test_IDTS_SAP01_{lang}_v0.3.xlsx",
    "report": "Test_Report_IDTS_SAP01_{lang}_v0.4.xlsx",
    "uat": "UAT_IDTS_SAP01_{lang}_prepared_v0.2.xlsx",
    "defect": "Test_And_Fix_Bug_IDTS_SAP01_{lang}_v0.5.xlsx",
}


class Validation:
    def __init__(self):
        self.errors = []
        self.warnings = []

    def fail(self, message):
        self.errors.append(message)

    def warn(self, message):
        self.warnings.append(message)


def local(value, lang):
    if isinstance(value, dict):
        return str(value.get(lang) or "")
    return "" if value is None else str(value)


def validate_catalog(catalog, result):
    cases = catalog.get("cases", [])
    requirements = {item["id"] for item in catalog.get("requirements", [])}
    case_ids = [case.get("caseId") for case in cases]
    duplicates = [
        case_id for case_id, count in Counter(case_ids).items() if count > 1
    ]
    if duplicates:
        result.fail(f"Duplicate case IDs: {duplicates}")
    defect_ids = {defect.get("defectId") for defect in catalog.get("defects", [])}

    for case in cases:
        case_id = case.get("caseId", "<missing>")
        missing = sorted(REQUIRED_CASE_FIELDS - set(case))
        if missing:
            result.fail(f"{case_id}: missing fields {missing}")
        if not case.get("requirementIds"):
            result.fail(f"{case_id}: no requirement ID")
        for requirement_id in case.get("requirementIds", []):
            if requirement_id not in requirements:
                result.fail(f"{case_id}: unknown requirement {requirement_id}")
        if case.get("status") not in VALID_STATUSES:
            result.fail(f"{case_id}: invalid status {case.get('status')}")
        for lang in ("en", "vi"):
            for field in (
                "title",
                "objective",
                "preconditions",
                "testData",
                "expectedResult",
                "postcondition",
            ):
                if not local(case.get(field), lang).strip():
                    result.fail(f"{case_id}: missing {lang} {field}")
            steps = case.get("steps", {}).get(lang, [])
            if not steps or any(not str(step).strip() for step in steps):
                result.fail(f"{case_id}: missing {lang} steps")
        if case.get("status") == "PASSED":
            for field in ("actualResult", "executor", "executionDate", "evidenceLinks"):
                value = case.get(field)
                if not value or (
                    isinstance(value, dict) and not value.get("en")
                ):
                    result.fail(f"{case_id}: PASSED without {field}")
        if case.get("status") in {"NOT_RUN", "PENDING", "PREPARED"}:
            if local(case.get("actualResult"), "en").strip():
                result.fail(
                    f"{case_id}: {case.get('status')} has an actual-result claim"
                )
        for defect_id in case.get("defectIds", []):
            if defect_id not in defect_ids:
                result.fail(f"{case_id}: unknown defect {defect_id}")

    for defect in catalog.get("defects", []):
        defect_id = defect.get("defectId", "<missing>")
        required = (
            "summary",
            "classification",
            "stepsToReproduce",
            "preconditions",
            "expectedResult",
            "actualResult",
            "environment",
            "severity",
            "priority",
            "reporter",
            "owner",
            "discoveredDate",
            "status",
            "rootCause",
            "fixDescription",
            "requirementIds",
            "testCaseIds",
            "evidenceLinks",
            "retestCommand",
            "retestResult",
            "retestDate",
            "closedDate",
            "remainingAction",
        )
        for field in required:
            if field not in defect or defect[field] in (None, "", []):
                result.fail(f"{defect_id}: missing {field}")
        for case_id in defect.get("testCaseIds", []):
            if case_id not in case_ids:
                result.fail(f"{defect_id}: unknown related test case {case_id}")

    covered = {
        requirement_id
        for case in cases
        for requirement_id in case.get("requirementIds", [])
    }
    for requirement_id in sorted(requirements - covered):
        result.warn(f"Requirement {requirement_id}: NOT COVERED")


def iter_text_cells(wb):
    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                if cell.value is not None:
                    yield ws, cell, str(cell.value)


def merged_width(ws, cell):
    for merged in ws.merged_cells.ranges:
        if cell.coordinate in merged:
            return sum(
                ws.column_dimensions[get_column_letter(column)].width or 13
                for column in range(merged.min_col, merged.max_col + 1)
            )
    return ws.column_dimensions[cell.column_letter].width or 13


def validate_workbook(path, result):
    try:
        wb = load_workbook(path, data_only=False)
    except Exception as exc:
        result.fail(f"{path.name}: cannot open ({exc})")
        return

    for item in wb.defined_names.values():
        if "#REF!" in (item.attr_text or ""):
            result.fail(f"{path.name}: broken defined name {item.name}")
    normal_style = next(
        (style for style in wb._named_styles if style.name == "Normal"),
        None,
    )
    if normal_style is None or float(normal_style.font.sz or 11) < 12:
        result.fail(f"{path.name}: workbook Normal style must be at least 12pt")

    for ws in wb.worksheets:
        if ws.max_row > 200:
            result.fail(
                f"{path.name}/{ws.title}: excessive formatted rows ({ws.max_row})"
            )
        if ws.max_column > 100:
            result.fail(
                f"{path.name}/{ws.title}: excessive formatted columns ({ws.max_column})"
            )
        for row_number, dimension in ws.row_dimensions.items():
            allowed_height = (
                140
                if path.name.startswith("Test_Scenario_")
                and ws.title == "Test Cases"
                and 8 <= row_number <= 28
                else 170
                if path.name.startswith("Unit_Test_")
                and ws.title == "UT"
                and 8 <= row_number <= 12
                else 170
                if path.name.startswith("UAT_")
                and ws.title == "Test Cases"
                and 8 <= row_number <= 13
                else 190
                if path.name.startswith("Functional_Test_")
                and ws.title == "Test Cases"
                and 8 <= row_number <= 23
                else 100
                if path.name.startswith("Functional_Test_")
                and ws.title == "Test Result"
                and 5 <= row_number <= 16
                else 120
                if path.name.startswith("Test_And_Fix_Bug_")
                and ws.title == "Fix and bugs"
                else 110
                if path.name.startswith("Test_Report_")
                and ws.title in {"Feature 1", "Feature 2"}
                else 90
            )
            if dimension.height and dimension.height > allowed_height:
                result.fail(
                    f"{path.name}/{ws.title}: row {row_number} "
                    f"height {dimension.height} > {allowed_height}"
                )
        under_12 = []
        for row in ws.iter_rows():
            for cell in row:
                if isinstance(cell, MergedCell):
                    continue
                if (
                    cell.value not in (None, "")
                    and float(cell.font.sz or 11) < 12
                ):
                    under_12.append(
                        f"{cell.coordinate}:{float(cell.font.sz or 11):g}pt"
                    )
                alignment = cell.alignment
                if alignment and alignment.text_rotation not in (0, None):
                    result.fail(
                        f"{path.name}/{ws.title}!{cell.coordinate}: "
                        "rotated/vertical text"
                    )
                if (
                    isinstance(cell.value, str)
                    and len(cell.value.strip()) >= 12
                    and alignment
                    and alignment.wrap_text
                    and merged_width(ws, cell) < 4
                ):
                    result.fail(
                        f"{path.name}/{ws.title}!{cell.coordinate}: "
                        "probable vertical character wrapping"
                    )
        if under_12:
            result.fail(
                f"{path.name}/{ws.title}: {len(under_12)} populated cells "
                f"below 12pt; sample {', '.join(under_12[:8])}"
            )
        if ws.title != "Cover":
            if not ws.print_area:
                result.fail(f"{path.name}/{ws.title}: missing print area")
            if ws.freeze_panes is None:
                result.fail(f"{path.name}/{ws.title}: missing frozen header")
            if ws.auto_filter.ref is not None:
                result.fail(
                    f"{path.name}/{ws.title}: unexpected worksheet filter "
                    f"{ws.auto_filter.ref}"
                )
            for table in ws.tables.values():
                if table.autoFilter is not None:
                    result.fail(
                        f"{path.name}/{ws.title}: unexpected table filter "
                        f"{table.name} ({table.ref})"
                    )

    for ws, cell, value in iter_text_cells(wb):
        for pattern in FORBIDDEN:
            if pattern.search(value):
                result.fail(
                    f"{path.name}/{ws.title}!{cell.coordinate}: "
                    f"forbidden token {pattern.pattern}"
                )
        if "_vi_" in path.name and value.strip() in VI_UNTRANSLATED_EXACT:
            result.fail(
                f"{path.name}/{ws.title}!{cell.coordinate}: "
                f"untranslated template label {value!r}"
            )
    wb.close()


def case_ids_from_workbook(kind, path, result):
    try:
        wb = load_workbook(path, data_only=False)
        if kind == "scenario":
            values = [wb["Test Cases"][f"B{row}"].value for row in range(8, 29)]
        elif kind == "unit":
            values = [wb["UT"][f"B{row}"].value for row in range(8, 13)]
        elif kind == "functional":
            values = [
                wb["Test Cases"][f"B{row}"].value for row in range(8, 24)
            ]
        elif kind == "report":
            values = []
            for sheet_name in ("Feature 1", "Feature 2"):
                ws = wb[sheet_name]
                values.extend(
                    ws[f"A{row}"].value
                    for row in range(12, ws.max_row + 1)
                    if ws[f"A{row}"].value
                )
        elif kind == "uat":
            values = [wb["Test Cases"][f"B{row}"].value for row in range(8, 14)]
        else:
            values = []
            ws = wb["Fix and bugs"]
            for row in range(2, ws.max_row + 1):
                match = re.match(r"(IDTS-\d+)", str(ws[f"B{row}"].value or ""))
                if match:
                    values.append(match.group(1))
        wb.close()
        return [str(value) for value in values if value]
    except Exception as exc:
        result.fail(f"{path.name}: cannot extract IDs ({exc})")
        return []


def expected_ids(kind, catalog):
    if kind == "scenario":
        return [
            case["caseId"]
            for case in catalog["cases"]
            if case["testType"] != "UAT"
        ]
    if kind == "unit":
        return [
            case["caseId"]
            for case in catalog["cases"]
            if case["testType"] == "UNIT"
        ]
    if kind == "functional":
        return [
            case["caseId"]
            for case in catalog["cases"]
            if case["testType"] not in {"UNIT", "UAT"}
        ]
    if kind == "report":
        executed = [
            case["caseId"]
            for case in catalog["cases"]
            if case["status"] in {"PASSED", "FAILED", "BLOCKED"}
        ]
        pending = [
            case["caseId"]
            for case in catalog["cases"]
            if case["status"] not in {"PASSED", "FAILED", "BLOCKED"}
        ]
        return executed + pending
    if kind == "uat":
        return [
            case["caseId"]
            for case in catalog["cases"]
            if case["testType"] == "UAT"
        ]
    return [defect["defectId"] for defect in catalog["defects"]]


def validate_ids_and_parity(catalog, result):
    for kind, pattern in FILE_PATTERNS.items():
        expected = expected_ids(kind, catalog)
        language_ids = {}
        for lang in ("en", "vi"):
            path = OUTPUT_DIR / pattern.format(lang=lang)
            if not path.exists():
                result.fail(f"{kind}: missing {lang} workbook")
                continue
            ids = case_ids_from_workbook(kind, path, result)
            language_ids[lang] = ids
            if ids != expected:
                result.fail(
                    f"{path.name}: IDs differ from catalog "
                    f"({len(ids)} != {len(expected)})"
                )
            if len(ids) != len(set(ids)):
                result.fail(f"{path.name}: duplicate IDs")
        if language_ids.get("en") != language_ids.get("vi"):
            result.fail(f"{kind}: EN/VI ID parity mismatch")


def validate_case_content(catalog, result):
    case_by_id = {case["caseId"]: case for case in catalog["cases"]}
    for lang in ("en",):
        scenario_path = OUTPUT_DIR / FILE_PATTERNS["scenario"].format(lang=lang)
        scenario = load_workbook(scenario_path, data_only=False)["Test Cases"]
        for row in range(8, 29):
            case_id = scenario[f"B{row}"].value
            for column, field in (("E", "definition"), ("Y", "test data"), ("AP", "predicted result")):
                if not str(scenario[f"{column}{row}"].value or "").strip():
                    result.fail(
                        f"{scenario_path.name}: {case_id} missing {field}"
                    )
            if re.search(
                r"^(Expected|Mong đợi)\s*:",
                str(scenario[f"Y{row}"].value or ""),
                re.I,
            ):
                result.fail(
                    f"{scenario_path.name}: {case_id} expected result is in test data"
                )

        unit_path = OUTPUT_DIR / FILE_PATTERNS["unit"].format(lang=lang)
        unit = load_workbook(unit_path, data_only=False)["UT"]
        for row in range(8, 13):
            case_id = unit[f"B{row}"].value
            case = case_by_id[case_id]
            for column, field in (("E", "unit/setup/input"), ("Y", "assertion/output"), ("BL", "evidence")):
                if not str(unit[f"{column}{row}"].value or "").strip():
                    result.fail(f"{unit_path.name}: {case_id} missing {field}")
            if case["status"] == "PASSED":
                for column, field in (("AX", "executor"), ("BD", "date"), ("BJ", "status"), ("BL", "evidence")):
                    if not str(unit[f"{column}{row}"].value or "").strip():
                        result.fail(
                            f"{unit_path.name}: PASSED {case_id} missing {field}"
                        )

        functional_path = (
            OUTPUT_DIR / FILE_PATTERNS["functional"].format(lang=lang)
        )
        functional = load_workbook(functional_path, data_only=False)["Test Cases"]
        for row in range(8, 24):
            case_id = functional[f"B{row}"].value
            for column, field in (("E", "definition"), ("Y", "expected/actual"), ("BJ", "status"), ("BL", "evidence/limitation")):
                if not str(functional[f"{column}{row}"].value or "").strip():
                    result.fail(
                        f"{functional_path.name}: {case_id} missing {field}"
                    )

        uat_path = OUTPUT_DIR / FILE_PATTERNS["uat"].format(lang=lang)
        uat_book = load_workbook(uat_path, data_only=False)
        uat = uat_book["Test Cases"]
        for row in range(8, 14):
            case_id = uat[f"B{row}"].value
            for column, field in (("E", "definition"), ("Y", "test data"), ("AP", "predicted/acceptance")):
                if not str(uat[f"{column}{row}"].value or "").strip():
                    result.fail(f"{uat_path.name}: {case_id} missing {field}")
            for column, field in (("BO", "actual"), ("BU", "defect"), ("CA", "decision"), ("CC", "tester/date/sign-off")):
                if uat[f"{column}{row}"].value not in (None, ""):
                    result.fail(
                        f"{uat_path.name}: PREPARED {case_id} has fake {field}"
                    )
        result_sheet = uat_book["Test Result"]
        for row in range(3, 15, 2):
            for column in ("C", "I", "K", "M", "O"):
                if result_sheet[f"{column}{row}"].value not in (None, ""):
                    result.fail(
                        f"{uat_path.name}/Test Result!{column}{row}: "
                        "prepared execution field is not blank"
                    )
        uat_book.close()

        defect_path = OUTPUT_DIR / FILE_PATTERNS["defect"].format(lang=lang)
        defects = load_workbook(defect_path, data_only=False)
        if defects.sheetnames != ["Fix and bugs"]:
            result.fail(
                f"{defect_path.name}: unused Issue 2 / Issue 4 sheets remain"
            )
        defect_ws = defects["Fix and bugs"]
        found = 0
        for row in range(2, defect_ws.max_row + 1):
            if re.match(r"IDTS-\d+", str(defect_ws[f"B{row}"].value or "")):
                found += 1
                for column, field in (("B", "summary/ownership"), ("C", "reproduction"), ("D", "expected/traceability"), ("E", "fix/retest"), ("F", "evidence")):
                    if not str(defect_ws[f"{column}{row}"].value or "").strip():
                        result.fail(
                            f"{defect_path.name}: defect row {row} missing {field}"
                        )
        if found != len(catalog["defects"]):
            result.fail(
                f"{defect_path.name}: {found} defect rows != "
                f"{len(catalog['defects'])}"
            )
        defects.close()


def validate_report_metrics(catalog, result):
    statuses = Counter(case["status"] for case in catalog["cases"])
    planned = len(catalog["cases"])
    passed = statuses["PASSED"]
    failed = statuses["FAILED"]
    blocked = statuses["BLOCKED"]
    pending = statuses["NOT_RUN"] + statuses["PREPARED"] + statuses["PENDING"]
    executed = passed + failed
    linked = {
        requirement_id
        for case in catalog["cases"]
        for requirement_id in case["requirementIds"]
    }
    executed_requirements = {
        requirement_id
        for case in catalog["cases"]
        if case["status"] in {"PASSED", "FAILED"}
        for requirement_id in case["requirementIds"]
    }
    assertions = sum(
        run["passed"] + run["failed"] + run["skipped"]
        for run in catalog["executionRuns"]
    )
    expected_direct = [
        planned,
        executed,
        passed,
        failed,
        blocked,
        pending,
        len(linked) / len(catalog["requirements"]),
        len(executed_requirements) / len(catalog["requirements"]),
        assertions,
        len(catalog["defects"]),
    ]
    expected_cached = {
        "D14": passed,
        "E14": failed,
        "F14": pending,
        "G14": blocked,
        "H14": planned,
        "E16": executed / planned,
        "E17": passed / executed if executed else 0,
    }
    for lang in ("en",):
        path = OUTPUT_DIR / FILE_PATTERNS["report"].format(lang=lang)
        formula_book = load_workbook(path, data_only=False, read_only=True)
        formula_sheet = formula_book["Test Statistics"]
        if "execution rate" not in str(formula_sheet["C16"].value).lower() and "thực thi" not in str(formula_sheet["C16"].value).lower():
            result.fail(f"{path.name}: coverage label does not declare execution rate")
        for coordinate in ("F16", "F17"):
            if formula_sheet[coordinate].value not in (None, ""):
                result.fail(
                    f"{path.name}: {coordinate} must be blank because E16/E17 already use percentage number formatting"
                )
        formula_book.close()

        value_book = load_workbook(path, data_only=True, read_only=True)
        ws = value_book["Test Statistics"]
        actual_direct = [ws[f"C{row}"].value for row in range(20, 30)]
        for row, actual, expected in zip(
            range(20, 30), actual_direct, expected_direct
        ):
            if isinstance(expected, float):
                if actual is None or abs(float(actual) - expected) > 1e-8:
                    result.fail(
                        f"{path.name}: metric C{row} {actual} != {expected}"
                    )
            elif actual != expected:
                result.fail(
                    f"{path.name}: metric C{row} {actual} != {expected}"
                )
        for coordinate, expected in expected_cached.items():
            actual = ws[coordinate].value
            if actual is None:
                result.fail(
                    f"{path.name}: formula cached value missing at {coordinate}"
                )
            elif abs(float(actual) - expected) > 1e-8:
                result.fail(
                    f"{path.name}: {coordinate} {actual} != {expected}"
                )
        value_book.close()


def hyperlink_target_is_valid(wb, hyperlink):
    location = getattr(hyperlink, "location", None)
    external_target = getattr(hyperlink, "target", None)
    if external_target:
        return False
    target = location or getattr(hyperlink, "target", None)
    if not target or not str(target).startswith("#"):
        if location:
            target = f"#{unquote(str(location))}"
        else:
            return bool(target)
    match = re.fullmatch(r"#?'([^']+)'!([A-Z]+\d+)", unquote(str(target)))
    if not match:
        return False
    sheet_name, coordinate = match.groups()
    return (
        sheet_name in wb.sheetnames
        and wb[sheet_name][coordinate].value not in (None, "")
    )


def is_link_blue_without_link(cell):
    color = cell.font.color
    if cell.hyperlink or color is None:
        return False
    rgb = getattr(color, "rgb", None)
    return isinstance(rgb, str) and rgb[-6:].upper() in {"0563C1", "0000FF"}


def validate_evidence_contract(catalog, result):
    baseline = catalog.get("evidenceBaseline", {})
    runtime_sha = str(baseline.get("runtimeCommitSha") or "")
    evidence_sha = str(baseline.get("evidenceCommitSha") or "")
    if not re.fullmatch(r"[0-9a-f]{40}", runtime_sha):
        result.fail("Catalog evidence baseline has missing/placeholder runtime commit SHA")
    if not re.fullmatch(r"[0-9a-f]{40}", evidence_sha):
        result.fail("Catalog evidence baseline has missing/placeholder evidence commit SHA")

    for lang in ("en",):
        functional_path = OUTPUT_DIR / FILE_PATTERNS["functional"].format(lang=lang)
        functional_book = load_workbook(functional_path, data_only=False)
        runs = functional_book["Test Result"]
        if not str(runs["B5"].value or "").startswith("REG-"):
            result.fail(f"{functional_path.name}: first run must start in official row block B5")
        expected_last = 4 + len(catalog["executionRuns"]) * 2
        if runs.freeze_panes != "B5":
            result.fail(f"{functional_path.name}: Test Result freeze pane must be B5")
        if str(runs.print_area) != f"'Test Result'!$B$4:$BR${expected_last}":
            result.fail(f"{functional_path.name}: Test Result print area is stale")
        functional_book.close()

        report_path = OUTPUT_DIR / FILE_PATTERNS["report"].format(lang=lang)
        report_book = load_workbook(report_path, data_only=False)
        report_cases = report_book["Test Cases"]
        for row in range(9, 9 + len(catalog["cases"])):
            link_cell = report_cases[f"D{row}"]
            plain_cell = report_cases[f"E{row}"]
            if not link_cell.hyperlink or not hyperlink_target_is_valid(report_book, link_cell.hyperlink):
                result.fail(f"{report_path.name}/Test Cases!D{row}: broken or blank internal hyperlink")
            if is_link_blue_without_link(plain_cell):
                result.fail(f"{report_path.name}/Test Cases!E{row}: link styling without hyperlink")
            if plain_cell.hyperlink:
                result.fail(f"{report_path.name}/Test Cases!E{row}: unexpected hyperlink")
            if plain_cell.font.name != report_cases[f"F{row}"].font.name:
                result.fail(f"{report_path.name}/Test Cases!E{row}: font family differs from template row")
        report_book.close()

        unit_path = OUTPUT_DIR / FILE_PATTERNS["unit"].format(lang=lang)
        unit_book = load_workbook(unit_path, data_only=False)
        unit = unit_book["UT"]
        evidence = unit_book["Evidence"]
        for row, case in enumerate(
            [item for item in catalog["cases"] if item["testType"] == "UNIT"],
            8,
        ):
            link_cell = unit[f"BL{row}"]
            if not link_cell.hyperlink or not hyperlink_target_is_valid(unit_book, link_cell.hyperlink):
                result.fail(f"{unit_path.name}/UT!BL{row}: missing or broken case evidence link")
            evidence_row = row - 6
            if evidence[f"A{evidence_row}"].value != f"EVD-{case['caseId']}":
                result.fail(f"{unit_path.name}/Evidence!A{evidence_row}: wrong Evidence ID")
            if not re.fullmatch(r"[0-9a-f]{40}", str(evidence[f"E{evidence_row}"].value or "")):
                result.fail(f"{unit_path.name}/Evidence!E{evidence_row}: invalid baseline")
            artifact = str(evidence[f"K{evidence_row}"].value or "")
            artifact_link = evidence[f"K{evidence_row}"].hyperlink
            if artifact.startswith("scripts/") or not artifact_link:
                result.fail(f"{unit_path.name}/Evidence!K{evidence_row}: command/source-only evidence")
        unit_book.close()

    index_path = OUTPUT_DIR / "Integration_Evidence_Index_IDTS_SAP01_v0.1.xlsx"
    if not index_path.exists():
        result.fail(f"Missing workbook: {index_path.name}")
        return
    index_book = load_workbook(index_path, data_only=False)
    index = index_book["Evidence Index"]
    if index.max_row != len(catalog["cases"]) + 1:
        result.fail(f"{index_path.name}: case/evidence row count mismatch")
    for row, case in enumerate(catalog["cases"], 2):
        if index[f"A{row}"].value != f"EVD-{case['caseId']}":
            result.fail(f"{index_path.name}!A{row}: wrong Evidence ID")
        if not index[f"E{row}"].hyperlink or not index[f"K{row}"].hyperlink:
            result.fail(f"{index_path.name}: row {row} lacks baseline or artifact hyperlink")
        if case["status"] == "PASSED":
            required = ("E", "H", "I", "K")
            for column in required:
                value = str(index[f"{column}{row}"].value or "")
                if not value or "<" in value:
                    result.fail(f"{index_path.name}!{column}{row}: PASSED case lacks real evidence metadata")
    index_book.close()


def main():
    result = Validation()
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    validate_catalog(catalog, result)

    paths = [
        OUTPUT_DIR / pattern.format(lang=lang)
        for pattern in FILE_PATTERNS.values()
        for lang in ("en",)
    ]
    for path in paths:
        if not path.exists():
            result.fail(f"Missing workbook: {path.name}")
        else:
            validate_workbook(path, result)
    # IDTS-106 retires Vietnamese submission artifacts.  Record-level catalog
    # validation remains, but EN/VI workbook parity is no longer a release gate.
    validate_case_content(catalog, result)
    validate_report_metrics(catalog, result)
    validate_evidence_contract(catalog, result)

    print("SAP490 OFFICIAL-TEMPLATE TEST PACK VALIDATION")
    print(f"Catalog cases: {len(catalog.get('cases', []))}")
    print(f"Requirements: {len(catalog.get('requirements', []))}")
    print(f"Defects: {len(catalog.get('defects', []))}")
    print(f"Workbooks checked: {len(paths)}")
    print(f"Warnings: {len(result.warnings)}")
    for warning in result.warnings:
        print(f"WARN: {warning}")
    print(f"Errors: {len(result.errors)}")
    for error in result.errors:
        print(f"ERROR: {error}")
    print("RESULT: FAIL" if result.errors else "RESULT: PASS")
    return 1 if result.errors else 0


if __name__ == "__main__":
    sys.exit(main())
